### ISSUE TITLE
Radio and Checkbox docs examples

### ISSUE THREAD

**Issue by mrcnk** [insites-co/insites-ui#9]
Currently our Radio and Checkbox examples are broken. The fix would be pretty easy - to move them to a separate components in Documentation repo and provide `useState` to them. I'd really appreciate some help here.

https://insites-ui-docs.netlify.app/form/checkbox/
https://insites-ui-docs.netlify.app/form/radio/

https://github.com/insites-co/insites-ui-docs/blob/master/content/form/checkbox.mdx
https://github.com/insites-co/insites-ui-docs/blob/master/content/form/radio.mdx

**Comment by rago4** [comment]
Fixed, more details here 👉 https://github.com/insites-co/insites-ui-docs/pull/3/commits/262136e3dc223d6d821748b60f7b4528a625e12f

**Comment by mrcnk** [comment]
Thx 👍
